### ISSUE TITLE
Can you tell us which hardware you use?

### ISSUE THREAD

**Issue by MessyPaste** [zexupan/MuSE#1]
Thank you for your excellent work, which advocates this field a big step!

But We have some confusions about training hardwares:
Which GPU and GPU numbers do you use? v100? 2080TI? We got only two batch sizes in 2080Ti.

By the way, we will appreciate it if you can provide any pre-trained models later.

**Comment by zexupan** [comment]
Thanks for your interest in my work. I used distributed training with 2*Tesla V100 GPUs. Please email me using your organizational email id for the pre-trained models. My email address is pan_zexu<AT>u.nus.edu

**Comment by zexupan** [comment]
Thanks for your interest in my work. I used distributed training with 2*Tesla V100 GPUs. Please email me using your organizational email id for the pre-trained models. My email address is pan_zexu <at> u.nus.edu

**Comment by zexupan** [comment]
Thanks for your interest in my work. I used distributed training with 2*Tesla V100 GPUs. Please email me using your organizational email id for the pre-trained models. My email address is pan_zexu<AT>u.nus.edu

**Comment by zexupan** [comment]
Thanks for your interest in my work. I used distributed training with 2*Tesla V100 GPUs. Please email me using your organizational email id for the pre-trained models. My email address is pan_zexu at u.nus.edu

**Comment by MessyPaste** [comment]
Thank you!
